application: pizza-cat-image-map
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /pizza-cat.jpg
  static_files: static/pizza-cat.jpg
  upload: static/pizza-cat.jpg
